### ISSUE TITLE
Your coding functions

### ISSUE THREAD

**Issue by thetrad9** [mdbridge/bit-bucket#1]
Hi Mark,
Thanks a bunch for releasing all your code. Am a fan and been using Vocola now for 2mts.  

I've started recreating functions like `prekris` = {}, got the idea from Caster. 
How do u deal with curly braces, brackets etc. I've looked but can't find the right vocola file in your repo?
Thanks

**Comment by mdbridge** [comment]
I don't use voice commands for this, I use vocabulary words.

**Comment by mdbridge** [comment]
see https://github.com/mdbridge/bit-bucket/blob/master/voice/my_vocabulary/generate_symbols.rb;   Unfortunately symbols.in  doesn't seem to  have made it to bit bucket.    :-(

**Comment by soticoker** [comment]
Thanks for sharing. I  created my own custom functions for symbols in the end. 

Also still using & learning from your bit bucket. Nice 👌
